### ISSUE TITLE
コーポレートブログにするためのデザイン修正

### ISSUE THREAD

**Issue by emorima** [h2carrot/h2carrot.github.io#24]
@kcscarrot-hataoka @kcscarrot-ooki

- [ ] ヘッダー・フッターを修正
- [ ] カテゴリーにTech2つあるのを修正

自分で見て、デザインを恥ずかしいと感じる箇所がない感じでお願いします。

**Comment by emorima** [comment]
@kcscarrot-hataoka @kcscarrot-ooki

コーポレートサイト用にするドメインの対応が完了したので、
こちらのデザイン対応ができれば、リンク追加の依頼を出せます。

**Comment by h2carrot** [comment]
無事デザイン修正できました～！ 🎉
